# Generated by Django 5.2.4 on 2025-08-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_asset_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default_img.png', null=True, upload_to='event_asset'),
        ),
    ]
